version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tao
      POSTGRES_PASSWORD: 123456qwe
      POSTGRES_DB: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tao"]
      interval: 5s
      timeout: 3s
      retries: 5
